name: Node App Deploy to Heroku through Github Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Use node 
      uses: actions/checkout@v2   # Checkout the repository

      uses: setup-node@v2
      with:
        node-version: '22'  # Specify the Node.js version
        
    - name: Install dependencies
      run: npm install
    - name: run tests
      run: npm test
